export const modules = [
  {
    key: 'users',
    title: 'Users',
    endpoint: 'users',
    columns: ['id', 'name', 'email', 'phone', 'status'],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    readOnlyCreate: true,
    fieldSections: [
      { id: 'basic', title: 'Account Information', fields: ['name', 'email', 'phone'] },
      { id: 'status', title: 'Status', fields: ['status'] },
    ],
  },
  {
    key: 'vendors',
    title: 'Vendors',
    endpoint: 'vendors',
    columns: ['id', 'businessName', 'email', 'businessType', 'approvalStatus', 'status'],
    fields: [
      { name: 'businessName', label: 'Business Name', type: 'text', required: true },
      { name: 'ownerName', label: 'Owner Name', type: 'text' },
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'address', label: 'Address', type: 'textarea' },
      { name: 'businessType', label: 'Business Type', type: 'select', options: ['product', 'service', 'both'] },
      { name: 'approvalStatus', label: 'Approval Status', type: 'select', options: ['incomplete', 'pending', 'approved', 'rejected'] },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    readOnlyCreate: true,
    fieldSections: [
      { id: 'business', title: 'Business Details', description: 'Core vendor information', fields: ['businessName', 'ownerName', 'businessType'] },
      { id: 'contact', title: 'Contact Information', fields: ['email', 'phone', 'address'] },
      { id: 'status', title: 'Status', fields: ['approvalStatus', 'status'] },
    ],
  },
  {
    key: 'products',
    title: 'Products',
    endpoint: 'products',
    columns: ['id', 'name', 'category', 'price', 'rating', 'status'],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'text', required: true },
      { name: 'subcategory', label: 'Subcategory', type: 'text' },
      { name: 'price', label: 'Price', type: 'number', required: true },
      { name: 'type', label: 'Type', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'image', label: 'Image', type: 'image' },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'locationId', label: 'Location ID', type: 'text' },
      { name: 'vendorName', label: 'Vendor Name', type: 'text' },
      { name: 'availability', label: 'Availability', type: 'text' },
      { name: 'contactPhone', label: 'Contact Phone', type: 'text' },
      { name: 'contactEmail', label: 'Contact Email', type: 'email' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    fieldSections: [
      { id: 'basic', title: 'Product Details', description: 'Name, category, and pricing', fields: ['name', 'category', 'subcategory', 'type', 'price', 'description'] },
      { id: 'media', title: 'Images & Media', collapsible: true, fields: ['image'] },
      { id: 'location', title: 'Location & Vendor', fields: ['location', 'locationId', 'vendorName'] },
      { id: 'contact', title: 'Contact & Availability', fields: ['availability', 'contactPhone', 'contactEmail'] },
      { id: 'status', title: 'Publishing', fields: ['status'] },
    ],
  },
  {
    key: 'services',
    title: 'Services',
    endpoint: 'services',
    columns: ['id', 'name', 'category', 'city', 'rating', 'status'],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'text', required: true },
      { name: 'subcategory', label: 'Subcategory', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'image', label: 'Image', type: 'image' },
      { name: 'city', label: 'City', type: 'text' },
      { name: 'locationId', label: 'Location ID', type: 'text' },
      { name: 'workingHours', label: 'Working Hours', type: 'text' },
      { name: 'serviceArea', label: 'Service Area', type: 'text' },
      { name: 'price', label: 'Price', type: 'number' },
      { name: 'vendorName', label: 'Vendor Name', type: 'text' },
      { name: 'contactPhone', label: 'Contact Phone', type: 'text' },
      { name: 'contactEmail', label: 'Contact Email', type: 'email' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    fieldSections: [
      { id: 'basic', title: 'Service Details', fields: ['name', 'category', 'subcategory', 'description', 'price'] },
      { id: 'media', title: 'Images', fields: ['image'] },
      { id: 'schedule', title: 'Schedule & Coverage', fields: ['city', 'locationId', 'workingHours', 'serviceArea'] },
      { id: 'contact', title: 'Contact & Vendor', fields: ['vendorName', 'contactPhone', 'contactEmail'] },
      { id: 'status', title: 'Publishing', fields: ['status'] },
    ],
  },
  {
    key: 'brands',
    title: 'Brands',
    endpoint: 'brands',
    columns: ['id', 'name', 'status'],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'logo', label: 'Logo', type: 'image' },
      { name: 'coverBanner', label: 'Cover Banner', type: 'image' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'overview', label: 'Overview', type: 'textarea' },
      { name: 'website', label: 'Website', type: 'text' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    fieldSections: [
      { id: 'basic', title: 'Brand Identity', fields: ['name', 'website'] },
      { id: 'media', title: 'Brand Assets', fields: ['logo', 'coverBanner'] },
      { id: 'content', title: 'Descriptions', fields: ['description', 'overview'] },
      { id: 'status', title: 'Publishing', fields: ['status'] },
    ],
  },
  {
    key: 'orders',
    title: 'Orders',
    endpoint: 'orders',
    columns: ['id', 'orderNumber', 'userName', 'total', 'orderStatus', 'paymentStatus', 'status'],
    fields: [
      { name: 'orderNumber', label: 'Order Number', type: 'text' },
      { name: 'userName', label: 'Customer Name', type: 'text', required: true },
      { name: 'userEmail', label: 'Customer Email', type: 'email' },
      { name: 'total', label: 'Total', type: 'number', required: true },
      { name: 'shippingAddress', label: 'Shipping Address', type: 'textarea' },
      { name: 'orderStatus', label: 'Order Status', type: 'select', options: ['pending', 'confirmed', 'shipped', 'delivered', 'cancelled'] },
      { name: 'paymentStatus', label: 'Payment Status', type: 'select', options: ['pending', 'paid', 'failed', 'refunded'] },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    fieldSections: [
      { id: 'order', title: 'Order Information', fields: ['orderNumber', 'total'] },
      { id: 'customer', title: 'Customer Details', fields: ['userName', 'userEmail', 'shippingAddress'] },
      { id: 'status', title: 'Order & Payment Status', fields: ['orderStatus', 'paymentStatus', 'status'] },
    ],
  },
  {
    key: 'bookings',
    title: 'Bookings',
    endpoint: 'bookings',
    columns: ['id', 'bookingNumber', 'serviceName', 'userName', 'bookingStatus', 'status'],
    fields: [
      { name: 'bookingNumber', label: 'Booking Number', type: 'text' },
      { name: 'serviceName', label: 'Service Name', type: 'text', required: true },
      { name: 'serviceId', label: 'Service ID', type: 'number' },
      { name: 'userName', label: 'Customer Name', type: 'text', required: true },
      { name: 'userEmail', label: 'Customer Email', type: 'email' },
      { name: 'contactPhone', label: 'Contact Phone', type: 'text' },
      { name: 'bookingDate', label: 'Booking Date', type: 'date' },
      { name: 'timeSlot', label: 'Time Slot', type: 'text' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
      { name: 'bookingStatus', label: 'Booking Status', type: 'select', options: ['pending', 'confirmed', 'completed', 'cancelled'] },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    fieldSections: [
      { id: 'booking', title: 'Booking Details', fields: ['bookingNumber', 'serviceName', 'serviceId', 'bookingDate', 'timeSlot'] },
      { id: 'customer', title: 'Customer Information', fields: ['userName', 'userEmail', 'contactPhone', 'notes'] },
      { id: 'status', title: 'Status', fields: ['bookingStatus', 'status'] },
    ],
  },
  {
    key: 'reviews',
    title: 'Reviews',
    endpoint: 'reviews',
    columns: ['id', 'targetType', 'targetId', 'userName', 'rating', 'status'],
    fields: [
      { name: 'targetType', label: 'Target Type', type: 'select', options: ['product', 'service'], required: true },
      { name: 'targetId', label: 'Target ID', type: 'number', required: true },
      { name: 'userName', label: 'User Name', type: 'text', required: true },
      { name: 'rating', label: 'Rating', type: 'number', required: true },
      { name: 'comment', label: 'Comment', type: 'textarea' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    fieldSections: [
      { id: 'target', title: 'Review Target', fields: ['targetType', 'targetId'] },
      { id: 'content', title: 'Review Content', fields: ['userName', 'rating', 'comment'] },
      { id: 'status', title: 'Moderation', fields: ['status'] },
    ],
  },
  {
    key: 'banners',
    title: 'Banners',
    endpoint: 'banners',
    columns: ['id', 'title', 'position', 'sortOrder', 'status'],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'subtitle', label: 'Subtitle', type: 'text' },
      { name: 'image', label: 'Image', type: 'image', required: true },
      { name: 'link', label: 'Link URL', type: 'text' },
      { name: 'position', label: 'Position', type: 'select', options: ['home_hero', 'home_middle', 'home_bottom', 'sidebar'] },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    fieldSections: [
      { id: 'content', title: 'Banner Content', fields: ['title', 'subtitle', 'link'] },
      { id: 'media', title: 'Banner Image', fields: ['image'] },
      { id: 'placement', title: 'Placement & Order', fields: ['position', 'sortOrder'] },
      { id: 'status', title: 'Publishing', fields: ['status'] },
    ],
  },
  {
    key: 'faqs',
    title: 'FAQ',
    endpoint: 'faqs',
    columns: ['id', 'question', 'category', 'sortOrder', 'status'],
    fields: [
      { name: 'question', label: 'Question', type: 'text', required: true },
      { name: 'answer', label: 'Answer', type: 'textarea', required: true },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    fieldSections: [
      { id: 'content', title: 'FAQ Content', fields: ['question', 'answer', 'category'] },
      { id: 'order', title: 'Display Order', fields: ['sortOrder'] },
      { id: 'status', title: 'Publishing', fields: ['status'] },
    ],
  },
  {
    key: 'home-sections',
    title: 'Home Page Sections',
    endpoint: 'home-sections',
    columns: ['id', 'key', 'title', 'enabled', 'sortOrder', 'status'],
    fields: [
      { name: 'key', label: 'Section Key', type: 'text', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'subtitle', label: 'Subtitle', type: 'text' },
      { name: 'enabled', label: 'Enabled', type: 'boolean' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
      { name: 'band', label: 'Band', type: 'select', options: ['default', 'tinted', 'subtle'] },
      { name: 'viewAll', label: 'View All Link', type: 'text' },
      { name: 'fullWidth', label: 'Full Width', type: 'boolean' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    fieldSections: [
      { id: 'section', title: 'Section Identity', fields: ['key', 'title', 'subtitle'] },
      { id: 'layout', title: 'Layout & Display', fields: ['enabled', 'sortOrder', 'band', 'viewAll', 'fullWidth'] },
      { id: 'status', title: 'Publishing', fields: ['status'] },
    ],
  },
  {
    key: 'settings',
    title: 'Settings',
    endpoint: 'settings',
    columns: ['id', 'key', 'label', 'group', 'status'],
    fields: [
      { name: 'key', label: 'Key', type: 'text', required: true },
      { name: 'label', label: 'Label', type: 'text', required: true },
      { name: 'value', label: 'Value', type: 'textarea' },
      { name: 'type', label: 'Type', type: 'select', options: ['text', 'textarea', 'image', 'boolean', 'number', 'json'] },
      { name: 'group', label: 'Group', type: 'text' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    fieldSections: [
      { id: 'meta', title: 'Setting Metadata', fields: ['key', 'label', 'group', 'type'] },
      { id: 'value', title: 'Value', fields: ['value'] },
      { id: 'status', title: 'Status', fields: ['status'] },
    ],
  },
];

export const getModuleByKey = (key) => modules.find((m) => m.key === key);
